name: Setup Gradle Wrapper
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate Wrapper
      run: |
        gradle wrapper --gradle-version 8.2.2
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gradlew gradle/
        git commit -m "Add Gradle wrapper files"
        git push
